<?php
/**
 * Footer Template
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

if (cyberchimps_get_option('footer_show_toggle') == '1') { 
	
do_action('cyberchimps_before_footer_widgets'); ?>

<div id="footer-widgets" class="row-fluid">
  <div id="footer-widget-container" class="span12">
  <div class="row-fluid">
    <?php if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar('cyberchimps-footer-widgets')) : ?>
      
      
    <?php endif; ?>
    </div><!-- .row-fluid -->
  </div><!-- #footer-widget-container -->
</div><!-- #footer-widgets .row-fluid  -->

<?php do_action('cyberchimps_after_footer_widgets'); ?>

<?php } ?>	


</div><!-- #wrapper .container-fluid -->
<?php do_action('cyberchimps_before_footer_container'); ?>
<?php do_action('cyberchimps_after_wrapper'); ?>

<?php do_action('cyberchimps_after_footer_container'); ?>


</div><!-- container -->

<footer class="site-footer row-fluid">
	<div class="container">
	<div class="span9">
	<?php wp_nav_menu( array( 'theme_location'  => 'primary', 'depth => 1', 'menu_class' => 'nav nav-footer', 'fallback_cb' => 'cyberchimps_fallback_menu_footer' ) ); ?>
  </div>
  <div class="span3">
	<?php do_action('cyberchimps_footer'); ?>
	</div>
	</div>
</footer><!-- .site-footer .row-fluid -->

<?php wp_footer(); ?>

</body>
</html>